server:
  port: 8086

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: zerone-backend
          uri: lb://zerone-backend
          predicates:
            - Path=/api/v1/**
        - id: swagger-backend
          uri: lb://zerone-backend
          predicates:
            - Path=/swagger-ui/**
        - id: api-docs-backend
          uri: lb://zerone-backend
          predicates:
            - Path=/v3/api-docs/**
        - id: reports
          uri: lb://reports
          predicates:
            - Path=/reports/**
        - id: swagger-reports
          uri: lb://reports
          predicates:
            - Path=/swagger-ui/**
        - id: api-docs-reports
          uri: lb://reports
          predicates:
            - Path=/v3/api-docs/**

