server:
  port: 8086

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: zerone-backend
          uri: lb://zerone-backend
          predicates:
            - Path=/api/v1/**
        - id: swagger
          uri: lb://zerone-backend
          predicates:
            - Path=/swagger-ui/**
        - id: api-docs
          uri: lb://zerone-backend
          predicates:
            - Path=/v3/api-docs/**
        - id: reports
          uri: lb://reports
          predicates:
            - Path=/reports/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defoultZone: http://localhost:8761/eureka/
  instance:
    hostname: host.docker.internal
