server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
    filename: /tmp/positions.yaml
  # hold loki When the client connects

clients:
  - url: http://192.168.0.129:3100/loki/api/v1/push

scrape_configs:


- job_name: docker
  static_configs:
  - targets:
      - localhost
    labels:
      job: docker
      __path__: /var/lib/docker/containers/*/*log