server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: host.docker.internal
#    prefer-ip-address: true
#    lease-expiration-duration-in-seconds: 30
#    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false